/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CutRouteImport } from './routes/cut'
import { Route as SelectsRouteImport } from './routes/selects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoryRouteImport } from './routes/story'
import { Route as WatchRouteImport } from './routes/watch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CutRoute = CutRouteImport.update({
  id: '/cut',
  path: '/cut',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectsRoute = SelectsRouteImport.update({
  id: '/selects',
  path: '/selects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cut': typeof CutRoute
  '/selects': typeof SelectsRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/watch': typeof WatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cut': typeof CutRoute
  '/selects': typeof SelectsRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/watch': typeof WatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cut': typeof CutRoute
  '/selects': typeof SelectsRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/watch': typeof WatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/chat' | '/cut' | '/selects' | '/settings' | '/story' | '/watch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/cut' | '/selects' | '/settings' | '/story' | '/watch'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/cut'
    | '/selects'
    | '/settings'
    | '/story'
    | '/watch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CutRoute: typeof CutRoute
  SelectsRoute: typeof SelectsRoute
  SettingsRoute: typeof SettingsRoute
  StoryRoute: typeof StoryRoute
  WatchRoute: typeof WatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cut': {
      id: '/cut'
      path: '/cut'
      fullPath: '/cut'
      preLoaderRoute: typeof CutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selects': {
      id: '/selects'
      path: '/selects'
      fullPath: '/selects'
      preLoaderRoute: typeof SelectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CutRoute: CutRoute,
  SelectsRoute: SelectsRoute,
  SettingsRoute: SettingsRoute,
  StoryRoute: StoryRoute,
  WatchRoute: WatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
